print("Welcome to the Band Name Generator")
user_city = input("What's your name of the city you grew up in?\n")
print(user_city)
user_pet = input("What's your pet's name?\n")
print(user_pet)
print("Your band name could be " + user_city + " " + user_pet)
